name: Run Automation suite



on:
  push:
    branches: [ "main" ]



 workflow_dispatch:
   inputs:
      Username:
        description: enter umusic id
        default: kalaivani.kannappan@umusic.com
        required: true
      Secret:
        description: enter password
        required: true
   
jobs:
  build:



   runs-on: ubuntu-latest



   steps:
    -  uses: actions/checkout@v2
    - run: |
         bash ./Scripts/runpipeline.sh
      env:
         ID: ${{ github.event.inputs.Username }}
         SECRET_PDD: ${{ github.event.inputs.Secret }}



   - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        
    - name: Build with Maven
      run: export SECRET_PDD=$SECRET_PDD && mvn -B test --file pom.xml
